### PR TITLE
Add support for userInfo entries for Entities, Attributes and Relationships

### PR DESCRIPTION
**Pull request by no-itsbackpack**
Extended this pull to add more support https://github.com/infinitered/ruby-xcdm/pull/19

Related Rubymotion Community question http://community.rubymotion.com/t/rubymotion-magicalrecord-import/1412

### CODE REVIEW

**Comment by kemiller** [comment]
Hey there, thanks for doing this.  Your implementation looks sound.

Would you mind removing whitespace-only changes though? Makes the commit a bit harder to follow.

**Comment by paddingtonsbear** [comment]
sorry about that, my editor automatically removes white spaces. I think adding `?=w1` to the end of the pull url helps eliminate white space changes.
https://github.com/infinitered/ruby-xcdm/pull/20?w=1

**Comment by paddingtonsbear** [comment]
@kemiller do you still need me to remove the whitespace changes my pull made ?

**Comment by paddingtonsbear** [comment]
@kemiller any update on when this will get merged

**Pull request closed without merging**
